name: Tests
on: [push, pull_request]

jobs:
  runner-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - name: Test
        run: cd tests && go test -v
